### ISSUE TITLE
Async tnt

### ISSUE THREAD

**Issue by andreasdc** [CobbleSword/NachoSpigot#143]
Async tnt probably causes really quick client crash after exploding many tnts

**Comment by Elierrr** [comment]
Probably? You should test it before making an issue.

**Comment by andreasdc** [comment]
> Probably? You should test it before making an issue.

crash is sure, if disabling async tnt helps, can't tell

**Comment by Lucaskyy** [comment]
Async TNT does not crash your client. All it does is run the calculations async on the server.

**Comment by andreasdc** [comment]
BTW firing a lot of tnt will cause 100% cpu usage on all threads

**Comment by Lucaskyy** [comment]
That is, well.. obvious.

**Comment by andreasdc** [comment]
Probably unwanted behaviour

**Comment by Lucaskyy** [comment]
If it's unwanted then they shouldn't explode a lot of tnt? lol. You'll get 100% cpu usage either way, whether we async the calculations or not. The only way of getting it down is by reinventing the wheel for explosions, and I'm not going to do that since it's a waste of time and I absolutely don't know a thing about algebra x)
