### ISSUE TITLE
Weather desync.

### ISSUE THREAD

**Issue by LoganTheOverlord** [CobbleSword/NachoSpigot#3]
**Hello**,

I have an issue with weather. Whenever it starts to rain, client won't update until disconnected. It looks like it's raining, but sky is clear and it's sunny. It's both sunny and raining.

**Comment by ceezuns** [comment]
I was able to reproduce this, it seems like the commit that caused the issue was [49fede86ceb563d9c490f480c784b4495636e02e](https://github.com/CobbleSword/NachoSpigot/commit/49fede86ceb563d9c490f480c784b4495636e02e#diff-00e134e91069d1e919494d284b8880a4). Reverting back to the original solution corrects this issue, although it is not optimal.

**Comment by HeathLoganCampbell** [comment]
Mmmmh, just tested that patch and it seems to not fix it

**Comment by ceezuns** [comment]
> Mmmmh, just tested that patch and it seems to not fix it

Do yo want me to send a PR of what I did?

**Comment by HeathLoganCampbell** [comment]
Did you test it? and it works?

**Comment by CheekyRB** [comment]
I’m cheeky

**Comment by ceezuns** [comment]
Yes, I reverted back to the original solution and that fixes it.

**Comment by CyberFlameGO** [comment]
@HeathLoganCampbell Close

**Comment by Lucaskyy** [comment]
Fixed it current commit/release.

**Closing.**
