### ISSUE TITLE
Chunk problem when block placed in high place

### ISSUE THREAD

**Issue by benfiratkaya** [CobbleSword/NachoSpigot#81]
We found a chunk problem. It's not Nacho problem. This problem is also have in the paper.

We record a video:
https://www.youtube.com/watch?v=TAihNp9U5AE

**Comment by CyberFlameGO** [comment]
I don't understand what this problem is, please clarify, and can you give me a list of plugins on your server?

**Comment by TheGeyik** [comment]
It's occure when up and down is empty chunk or light update (not sure) drop fps heavily. You can try it on empty world (Like skyblock) and create a flat area like video. Then break a block close to center. That's it.

**Comment by vituluss** [comment]
This is a bug with your client not the server, it is a well known bug in minecraft 1.8 and happens when there is a large void below a plane of blocks. Can test in survival for the same results.

**Comment by TheGeyik** [comment]
It's happend on plot area so is there any way to cancel chunk updates packet sending? or any idea

**Comment by vituluss** [comment]
If you cancel the chunk update the block won't disappear. Just put blocks below the plane of stone.

**Comment by Lucaskyy** [comment]
This is because Minecraft is dumb and tries to update lighting for a couple of million blocks at one synchronously.
This is like @vituluss said, a client-side bug we **cannot** fix. This is fixed in Minecraft client 1.13 and above.
No, this does not hinder the server for what I know, only the client. Yes, this can crash someone's client, so yes you should scream at Mojang for not making such stupid and dumb mistakes.

Now have a good day :')
